In [ ]:
import pandas as pd
import numpy as np
df=pd.read_csv("/content/sample_data/Universities.csv")

In [ ]:
df

            Univ   SAT  Top10  Accept  SFRatio  Expenses  GradRate
0          Brown  1310     89      22       13     22704        94
1        CalTech  1415    100      25        6     63575        81
2            CMU  1260     62      59        9     25026        72
3       Columbia  1310     76      24       12     31510        88
4        Cornell  1280     83      33       13     21864        90
5      Dartmouth  1340     89      23       10     32162        95
6           Duke  1315     90      30       12     31585        95
7     Georgetown  1255     74      24       12     20126        92
8        Harvard  1400     91      14       11     39525        97
9   JohnsHopkins  1305     75      44        7     58691        87
10           MIT  1380     94      30       10     34870        91
11  Northwestern  1260     85      39       11     28052        89
12     NotreDame  1255     81      42       13     15122        94
13     PennState  1081     38      54       18     10185        80
14     Princeton  1375     91      14        8     30220        95
15        Purdue  1005     28      90       19      9066        69
16      Stanford  1360     90      20       12     36450        93
17      TexasA&M  1075     49      67       25      8704        67
18    UCBerkeley  1240     95      40       17     15140        78
19      UChicago  1290     75      50       13     38380        87
20     UMichigan  1180     65      68       16     15470        85
21         UPenn  1285     80      36       11     27553        90
22           UVA  1225     77      44       14     13349        92
23    UWisconsin  1085     40      69       15     11857        71
24          Yale  1375     95      19       11     43514        96

In [ ]:
df.set_index('Univ',inplace=True)

In [ ]:
df

               SAT  Top10  Accept  SFRatio  Expenses  GradRate
Univ
Brown         1310     89      22       13     22704        94
CalTech       1415    100      25        6     63575        81
CMU           1260     62      59        9     25026        72
Columbia      1310     76      24       12     31510        88
Cornell       1280     83      33       13     21864        90
Dartmouth     1340     89      23       10     32162        95
Duke          1315     90      30       12     31585        95
Georgetown    1255     74      24       12     20126        92
Harvard       1400     91      14       11     39525        97
JohnsHopkins  1305     75      44        7     58691        87
MIT           1380     94      30       10     34870        91
Northwestern  1260     85      39       11     28052        89
NotreDame     1255     81      42       13     15122        94
PennState     1081     38      54       18     10185        80
Princeton     1375     91      14        8     30220        95
Purdue        1005     28      90       19      9066        69
Stanford      1360     90      20       12     36450        93
TexasA&M      1075     49      67       25      8704        67
UCBerkeley    1240     95      40       17     15140        78
UChicago      1290     75      50       13     38380        87
UMichigan     1180     65      68       16     15470        85
UPenn         1285     80      36       11     27553        90
UVA           1225     77      44       14     13349        92
UWisconsin    1085     40      69       15     11857        71
Yale          1375     95      19       11     43514        96

In [ ]:
df.loc[:,['SAT','Top10']]

               SAT  Top10
Univ
Brown         1310     89
CalTech       1415    100
CMU           1260     62
Columbia      1310     76
Cornell       1280     83
Dartmouth     1340     89
Duke          1315     90
Georgetown    1255     74
Harvard       1400     91
JohnsHopkins  1305     75
MIT           1380     94
Northwestern  1260     85
NotreDame     1255     81
PennState     1081     38
Princeton     1375     91
Purdue        1005     28
Stanford      1360     90
TexasA&M      1075     49
UCBerkeley    1240     95
UChicago      1290     75
UMichigan     1180     65
UPenn         1285     80
UVA           1225     77
UWisconsin    1085     40
Yale          1375     95

In [ ]:
df.loc['Yale',['SAT']]

SAT    1375
Name: Yale, dtype: int64

In [ ]:
df['SAT']

Univ
Brown           1310
CalTech         1415
CMU             1260
Columbia        1310
Cornell         1280
Dartmouth       1340
Duke            1315
Georgetown      1255
Harvard         1400
JohnsHopkins    1305
MIT             1380
Northwestern    1260
NotreDame       1255
PennState       1081
Princeton       1375
Purdue          1005
Stanford        1360
TexasA&M        1075
UCBerkeley      1240
UChicago        1290
UMichigan       1180
UPenn           1285
UVA             1225
UWisconsin      1085
Yale            1375
Name: SAT, dtype: int64

In [ ]:
df.index

Index(['Brown', 'CalTech', 'CMU', 'Columbia', 'Cornell', 'Dartmouth', 'Duke',
       'Georgetown', 'Harvard', 'JohnsHopkins', 'MIT', 'Northwestern',
       'NotreDame', 'PennState', 'Princeton', 'Purdue', 'Stanford', 'TexasA&M',
       'UCBerkeley', 'UChicago', 'UMichigan', 'UPenn', 'UVA', 'UWisconsin',
       'Yale'],
      dtype='object', name='Univ')

In [ ]:
df.loc['Brown',:]

SAT          1310
Top10          89
Accept         22
SFRatio        13
Expenses    22704
GradRate       94
Name: Brown, dtype: int64

In [ ]:
df.loc['MIT','SAT']

np.int64(1380)

In [ ]:
df.loc['CMU',['SAT','GradRate']]

SAT         1260
GradRate      72
Name: CMU, dtype: int64

In [ ]:
df.loc[['Brown', 'CalTech', 'CMU'],['SAT','GradRate']]

          SAT  GradRate
Univ
Brown    1310        94
CalTech  1415        81
CMU      1260        72

In [ ]:
df.loc[df['SAT']>1300 ,['SAT','GradRate']]

               SAT  GradRate
Univ
Brown         1310        94
CalTech       1415        81
Columbia      1310        88
Dartmouth     1340        95
Duke          1315        95
Harvard       1400        97
JohnsHopkins  1305        87
MIT           1380        91
Princeton     1375        95
Stanford      1360        93
Yale          1375        96

In [ ]:
df[df['GradRate']>60]

               SAT  Top10  Accept  SFRatio  Expenses  GradRate
Univ
Brown         1310     89      22       13     22704        94
CalTech       1415    100      25        6     63575        81
CMU           1260     62      59        9     25026        72
Columbia      1310     76      24       12     31510        88
Cornell       1280     83      33       13     21864        90
Dartmouth     1340     89      23       10     32162        95
Duke          1315     90      30       12     31585        95
Georgetown    1255     74      24       12     20126        92
Harvard       1400     91      14       11     39525        97
JohnsHopkins  1305     75      44        7     58691        87
MIT           1380     94      30       10     34870        91
Northwestern  1260     85      39       11     28052        89
NotreDame     1255     81      42       13     15122        94
PennState     1081     38      54       18     10185        80
Princeton     1375     91      14        8     30220        95
Purdue        1005     28      90       19      9066        69
Stanford      1360     90      20       12     36450        93
TexasA&M      1075     49      67       25      8704        67
UCBerkeley    1240     95      40       17     15140        78
UChicago      1290     75      50       13     38380        87
UMichigan     1180     65      68       16     15470        85
UPenn         1285     80      36       11     27553        90
UVA           1225     77      44       14     13349        92
UWisconsin    1085     40      69       15     11857        71
Yale          1375     95      19       11     43514        96

In [ ]:
df[df['Top10']>90]

             SAT  Top10  Accept  SFRatio  Expenses  GradRate
Univ
CalTech     1415    100      25        6     63575        81
Harvard     1400     91      14       11     39525        97
MIT         1380     94      30       10     34870        91
Princeton   1375     91      14        8     30220        95
UCBerkeley  1240     95      40       17     15140        78
Yale        1375     95      19       11     43514        96

In [ ]:
df[df['SAT']>1300].index

Index(['Brown', 'CalTech', 'Columbia', 'Dartmouth', 'Duke', 'Harvard',
       'JohnsHopkins', 'MIT', 'Princeton', 'Stanford', 'Yale'],
      dtype='object', name='Univ')

In [ ]:
df.loc[df['SAT']>1300,['SAT','GradRate']]

               SAT  GradRate
Univ
Brown         1310        94
CalTech       1415        81
Columbia      1310        88
Dartmouth     1340        95
Duke          1315        95
Harvard       1400        97
JohnsHopkins  1305        87
MIT           1380        91
Princeton     1375        95
Stanford      1360        93
Yale          1375        96

In [ ]:
df.loc[df['GradRate']>90,['GradRate']]

            GradRate
Univ
Brown             94
Dartmouth         95
Duke              95
Georgetown        92
Harvard           97
MIT               91
NotreDame         94
Princeton         95
Stanford          93
UVA               92
Yale              96

In [ ]:
df.loc[['Brown','Harvard','Yale'],['SAT']]

          SAT
Univ
Brown    1310
Harvard  1400
Yale     1375

In [ ]:
df.loc[df['GradRate'] > 90, ['GradRate']]

            GradRate
Univ
Brown             94
Dartmouth         95
Duke              95
Georgetown        92
Harvard           97
MIT               91
NotreDame         94
Princeton         95
Stanford          93
UVA               92
Yale              96

In [ ]:
df.iloc[0]
df.iloc[3]

SAT          1310
Top10          76
Accept         24
SFRatio        12
Expenses    31510
GradRate       88
Name: Columbia, dtype: int64

In [ ]:
df.iloc[0:6]

            SAT  Top10  Accept  SFRatio  Expenses  GradRate
Univ
Brown      1310     89      22       13     22704        94
CalTech    1415    100      25        6     63575        81
CMU        1260     62      59        9     25026        72
Columbia   1310     76      24       12     31510        88
Cornell    1280     83      33       13     21864        90
Dartmouth  1340     89      23       10     32162        95

In [ ]:
df.iloc[[0,2,4]]

          SAT  Top10  Accept  SFRatio  Expenses  GradRate
Univ
Brown    1310     89      22       13     22704        94
CMU      1260     62      59        9     25026        72
Cornell  1280     83      33       13     21864        90

In [ ]:
df.iloc[0,0]

np.int64(1310)

In [ ]:
df[(df['SAT']>1300 )& (df['GradRate']>90)].loc[:,['SAT','GradRate']]

            SAT  GradRate
Univ
Brown      1310        94
Dartmouth  1340        95
Duke       1315        95
Harvard    1400        97
MIT        1380        91
Princeton  1375        95
Stanford   1360        93
Yale       1375        96

In [ ]:
df[(df['SAT'] > 1300 ) & (df['GradRate'] > 90)].loc[:,'SAT']

Univ
Brown        1310
Dartmouth    1340
Duke         1315
Harvard      1400
MIT          1380
Princeton    1375
Stanford     1360
Yale         1375
Name: SAT, dtype: int64

In [ ]:
df.iloc[0:4,[2,3]]

          Accept  SFRatio
Univ
Brown         22       13
CalTech       25        6
CMU           59        9
Columbia      24       12

In [ ]:
df[df['SAT']==1315].loc[:,['SAT','Expenses']]

       SAT  Expenses
Univ
Duke  1315     31585

In [ ]:
df.loc['Cornell','GradRate']

np.int64(90)

In [ ]:
df.loc[['CalTech', 'MIT','Yale'],['Expenses']]

         Expenses
Univ
CalTech     63575
MIT         34870
Yale        43514

In [ ]:
df[(df['Top10']>=70) & (df['Top10']<=80)]

               SAT  Top10  Accept  SFRatio  Expenses  GradRate
Univ
Columbia      1310     76      24       12     31510        88
Georgetown    1255     74      24       12     20126        92
JohnsHopkins  1305     75      44        7     58691        87
UChicago      1290     75      50       13     38380        87
UPenn         1285     80      36       11     27553        90
UVA           1225     77      44       14     13349        92

In [ ]:
#GradRate is greater than 90 and SF ratio is less than 15.
df[(df['GradRate']>95) & (df['SFRatio']<15)]

          SAT  Top10  Accept  SFRatio  Expenses  GradRate
Univ
Harvard  1400     91      14       11     39525        97
Yale     1375     95      19       11     43514        96

Handling Null Values

In [ ]:
data = {
    'Name': ['Ravi', 'Priya', 'Arun', 'Sneha', 'Kiran', 'Anu'],
    'Age': [25, np.nan, 24, 30, np.nan, 29],
    'Salary': [30000, 45000, np.nan, 55000, 40000, np.nan],
    'Department': ['IT', np.nan, 'HR', np.nan, 'HR', 'IT']
}
df = pd.DataFrame(data)
df

    Name   Age   Salary Department
0   Ravi  25.0  30000.0         IT
1  Priya   NaN  45000.0        NaN
2   Arun  24.0      NaN         HR
3  Sneha  30.0  55000.0        NaN
4  Kiran   NaN  40000.0         HR
5    Anu  29.0      NaN         IT

In [ ]:
df.isnull().sum()

Name          0
Age           2
Salary        2
Department    2
dtype: int64

In [ ]:
df.isnull().sum().sum()

np.int64(6)

In [ ]:
df.isnull().any()

Name          False
Age            True
Salary         True
Department     True
dtype: bool

In [ ]:
df['Age'].isnull()

0    False
1     True
2    False
3    False
4     True
5    False
Name: Age, dtype: bool

In [ ]:
df[df['Age'].isnull()]

    Name  Age   Salary Department
1  Priya  NaN  45000.0        NaN
4  Kiran  NaN  40000.0         HR

In [ ]:
df['Age'].fillna(28)

0    25.0
1    28.0
2    24.0
3    30.0
4    28.0
5    29.0
Name: Age, dtype: float64

In [ ]:
df['Department'].fillna('Unknown')

0         IT
1    Unknown
2         IT
3    Unknown
4         HR
5         IT
Name: Department, dtype: object

0    42500.0
1    42500.0
2    42500.0
3    42500.0
4    42500.0
5    42500.0
Name: Salary, dtype: float64

np.float64(42500.0)

In [ ]:
df['Salary']

0    30000.0
1    45000.0
2        NaN
3    55000.0
4    40000.0
5        NaN
Name: Salary, dtype: float64

In [ ]:
avg_sal=df['Salary'].mean()
avg_sal
median_age=df['Age'].median()
median_age
mode_dept=df['Department'].mode()[1]
mode_dept

'IT'

In [ ]:
df.fillna({'Salary':avg_sal,'Age':median_age,'Department':mode_dept},inplace=True)

In [ ]:
df

    Name   Age   Salary Department
0   Ravi  25.0  30000.0         IT
1  Priya   NaN  45000.0        NaN
2   Arun  24.0      NaN         HR
3  Sneha  30.0  55000.0        NaN
4  Kiran   NaN  40000.0         HR
5    Anu  29.0      NaN         IT

In [ ]:
df

    Name   Age   Salary Department
0   Ravi  25.0  30000.0         IT
1  Priya  27.0  45000.0         IT
2   Arun  24.0  42500.0         HR
3  Sneha  30.0  55000.0         IT
4  Kiran  27.0  40000.0         HR
5    Anu  29.0  42500.0         IT

In [ ]:
df.dropna()

    Name   Age   Salary Department
0   Ravi  25.0  30000.0         IT
1  Priya  27.0  45000.0         IT
2   Arun  24.0  42500.0         HR
3  Sneha  30.0  55000.0         IT
4  Kiran  27.0  40000.0         HR
5    Anu  29.0  42500.0         IT

In [ ]:
import pandas as pd

data = {
    'Name': ['Ravi', 'Priya', 'Arun', 'Sneha', 'Ravi', 'Kiran', 'Priya'],
    'Age': [25, 28, 24, 30, 25, 26, 28],
    'Salary': [30000, 45000, 28000, 55000, 30000, 40000, 45000],
    'Department': ['IT', 'HR', 'IT', 'Finance', 'IT', 'HR', 'HR']
}

df = pd.DataFrame(data)

df

    Name  Age  Salary Department
0   Ravi   25   30000         IT
1  Priya   28   45000         HR
2   Arun   24   28000         IT
3  Sneha   30   55000    Finance
4   Ravi   25   30000         IT
5  Kiran   26   40000         HR
6  Priya   28   45000         HR

In [ ]:
df.duplicated()

0    False
1    False
2    False
3    False
4     True
5    False
6     True
dtype: bool

In [ ]:
df.duplicated().sum()

np.int64(2)

In [ ]:
df[df.duplicated(keep=False)]

    Name  Age  Salary Department
0   Ravi   25   30000         IT
1  Priya   28   45000         HR
4   Ravi   25   30000         IT
6  Priya   28   45000         HR

In [ ]:
df.drop_duplicates()

    Name  Age  Salary Department
0   Ravi   25   30000         IT
1  Priya   28   45000         HR
2   Arun   24   28000         IT
3  Sneha   30   55000    Finance
5  Kiran   26   40000         HR

In [ ]:
df['Name'].duplicated().sum()

np.int64(2)

In [ ]:
df[['Name','Department']].drop_duplicates()

    Name Department
0   Ravi         IT
1  Priya         HR
2   Arun         IT
3  Sneha    Finance
5  Kiran         HR

In [ ]:
employees1 = pd.DataFrame({
    'Emp_ID': [101, 102, 103, 104],
    'Name': ['Ravi', 'Anu', 'Kiran', 'Sita'],
    'Department': ['IT', 'HR', 'Finance', 'IT']
})


employees2 = pd.DataFrame({
    'Emp_ID': [105, 106, 107],
    'Name': ['Arjun', 'Priya', 'Rahul'],
    'Department': ['HR', 'Finance', 'Marketing']
})

In [ ]:
pd.concat([employees1,employees2],ignore_index=True)

   Emp_ID   Name Department
0     101   Ravi         IT
1     102    Anu         HR
2     103  Kiran    Finance
3     104   Sita         IT
4     105  Arjun         HR
5     106  Priya    Finance
6     107  Rahul  Marketing

In [ ]:
departments = pd.DataFrame({
    'Department': ['IT', 'HR', 'Finance', 'Sales'],
    'Employees': [25, 12, 18, 20]
})

managers = pd.DataFrame({
    'Manager': ['Ravi', 'Anu', 'Kiran', 'Suresh'],
    'Experience': [8, 6, 10, 7]
})

departments.join(managers)

  Department  Employees Manager  Experience
0         IT         25    Ravi           8
1         HR         12     Anu           6
2    Finance         18   Kiran          10
3      Sales         20  Suresh           7

In [ ]:
df1=pd.DataFrame({'eid':[1,2,3,4],
                  'ename':['a','b','c','d'],
                  'role':['e','f','g','h']})
df1

   eid ename role
0    1     a    e
1    2     b    f
2    3     c    g
3    4     d    h

In [ ]:
import numpy as np
df2=pd.DataFrame({'eid':[1,2,3,np.nan],
                  'ecom':['x','y','z','l'],
                  'roles':['z','c','b','g']})
df2

   eid ecom roles
0  1.0    x     z
1  2.0    y     c
2  3.0    z     b
3  NaN    l     g

In [ ]:
pd.merge(df1,df2,on='eid')

   eid ename role ecom roles
0    1     a    e    x     z
1    2     b    f    y     c
2    3     c    g    z     b

In [ ]:
pd.merge(df1,df2,on='eid',how='right')

   eid ename role ecom roles
0  1.0     a    e    x     z
1  2.0     b    f    y     c
2  3.0     c    g    z     b
3  NaN   NaN  NaN    l     g

In [ ]:
pd.merge(df1,df2,on='eid',how='left')

   eid ename role ecom roles
0    1     a    e    x     z
1    2     b    f    y     c
2    3     c    g    z     b
3    4     d    h  NaN   NaN

In [ ]:
pd.merge(df1,df2,on='eid',how='inner')

   eid ename role ecom roles
0    1     a    e    x     z
1    2     b    f    y     c
2    3     c    g    z     b

In [ ]:
pd.merge(df1,df2,on='eid',how='outer')

   eid ename role ecom roles
0  1.0     a    e    x     z
1  2.0     b    f    y     c
2  3.0     c    g    z     b
3  4.0     d    h  NaN   NaN
4  NaN   NaN  NaN    l     g

In [ ]:
df

            Univ   SAT  Top10  Accept  SFRatio  Expenses  GradRate
0          Brown  1310     89      22       13     22704        94
1        CalTech  1415    100      25        6     63575        81
2            CMU  1260     62      59        9     25026        72
3       Columbia  1310     76      24       12     31510        88
4        Cornell  1280     83      33       13     21864        90
5      Dartmouth  1340     89      23       10     32162        95
6           Duke  1315     90      30       12     31585        95
7     Georgetown  1255     74      24       12     20126        92
8        Harvard  1400     91      14       11     39525        97
9   JohnsHopkins  1305     75      44        7     58691        87
10           MIT  1380     94      30       10     34870        91
11  Northwestern  1260     85      39       11     28052        89
12     NotreDame  1255     81      42       13     15122        94
13     PennState  1081     38      54       18     10185        80
14     Princeton  1375     91      14        8     30220        95
15        Purdue  1005     28      90       19      9066        69
16      Stanford  1360     90      20       12     36450        93
17      TexasA&M  1075     49      67       25      8704        67
18    UCBerkeley  1240     95      40       17     15140        78
19      UChicago  1290     75      50       13     38380        87
20     UMichigan  1180     65      68       16     15470        85
21         UPenn  1285     80      36       11     27553        90
22           UVA  1225     77      44       14     13349        92
23    UWisconsin  1085     40      69       15     11857        71
24          Yale  1375     95      19       11     43514        96

In [ ]:
df.sort_values(by='SAT',ignore_index=True)

            Univ   SAT  Top10  Accept  SFRatio  Expenses  GradRate
0         Purdue  1005     28      90       19      9066        69
1       TexasA&M  1075     49      67       25      8704        67
2      PennState  1081     38      54       18     10185        80
3     UWisconsin  1085     40      69       15     11857        71
4      UMichigan  1180     65      68       16     15470        85
5            UVA  1225     77      44       14     13349        92
6     UCBerkeley  1240     95      40       17     15140        78
7     Georgetown  1255     74      24       12     20126        92
8      NotreDame  1255     81      42       13     15122        94
9   Northwestern  1260     85      39       11     28052        89
10           CMU  1260     62      59        9     25026        72
11       Cornell  1280     83      33       13     21864        90
12         UPenn  1285     80      36       11     27553        90
13      UChicago  1290     75      50       13     38380        87
14  JohnsHopkins  1305     75      44        7     58691        87
15         Brown  1310     89      22       13     22704        94
16      Columbia  1310     76      24       12     31510        88
17          Duke  1315     90      30       12     31585        95
18     Dartmouth  1340     89      23       10     32162        95
19      Stanford  1360     90      20       12     36450        93
20          Yale  1375     95      19       11     43514        96
21     Princeton  1375     91      14        8     30220        95
22           MIT  1380     94      30       10     34870        91
23       Harvard  1400     91      14       11     39525        97
24       CalTech  1415    100      25        6     63575        81

In [ ]:
df.sort_values(by='GradRate',ascending=False)

            Univ   SAT  Top10  Accept  SFRatio  Expenses  GradRate
8        Harvard  1400     91      14       11     39525        97
24          Yale  1375     95      19       11     43514        96
6           Duke  1315     90      30       12     31585        95
14     Princeton  1375     91      14        8     30220        95
5      Dartmouth  1340     89      23       10     32162        95
0          Brown  1310     89      22       13     22704        94
12     NotreDame  1255     81      42       13     15122        94
16      Stanford  1360     90      20       12     36450        93
7     Georgetown  1255     74      24       12     20126        92
22           UVA  1225     77      44       14     13349        92
10           MIT  1380     94      30       10     34870        91
21         UPenn  1285     80      36       11     27553        90
4        Cornell  1280     83      33       13     21864        90
11  Northwestern  1260     85      39       11     28052        89
3       Columbia  1310     76      24       12     31510        88
9   JohnsHopkins  1305     75      44        7     58691        87
19      UChicago  1290     75      50       13     38380        87
20     UMichigan  1180     65      68       16     15470        85
1        CalTech  1415    100      25        6     63575        81
13     PennState  1081     38      54       18     10185        80
18    UCBerkeley  1240     95      40       17     15140        78
2            CMU  1260     62      59        9     25026        72
23    UWisconsin  1085     40      69       15     11857        71
15        Purdue  1005     28      90       19      9066        69
17      TexasA&M  1075     49      67       25      8704        67

In [ ]:
df['Univ Rating']=df['GradRate'].apply(lambda x:'Excellent' if x>85 else 'Good')
df

            Univ   SAT  Top10  Accept  SFRatio  Expenses  GradRate Univ Rating
0          Brown  1310     89      22       13     22704        94   Excellent
1        CalTech  1415    100      25        6     63575        81        Good
2            CMU  1260     62      59        9     25026        72        Good
3       Columbia  1310     76      24       12     31510        88   Excellent
4        Cornell  1280     83      33       13     21864        90   Excellent
5      Dartmouth  1340     89      23       10     32162        95   Excellent
6           Duke  1315     90      30       12     31585        95   Excellent
7     Georgetown  1255     74      24       12     20126        92   Excellent
8        Harvard  1400     91      14       11     39525        97   Excellent
9   JohnsHopkins  1305     75      44        7     58691        87   Excellent
10           MIT  1380     94      30       10     34870        91   Excellent
11  Northwestern  1260     85      39       11     28052        89   Excellent
12     NotreDame  1255     81      42       13     15122        94   Excellent
13     PennState  1081     38      54       18     10185        80        Good
14     Princeton  1375     91      14        8     30220        95   Excellent
15        Purdue  1005     28      90       19      9066        69        Good
16      Stanford  1360     90      20       12     36450        93   Excellent
17      TexasA&M  1075     49      67       25      8704        67        Good
18    UCBerkeley  1240     95      40       17     15140        78        Good
19      UChicago  1290     75      50       13     38380        87   Excellent
20     UMichigan  1180     65      68       16     15470        85        Good
21         UPenn  1285     80      36       11     27553        90   Excellent
22           UVA  1225     77      44       14     13349        92   Excellent
23    UWisconsin  1085     40      69       15     11857        71        Good
24          Yale  1375     95      19       11     43514        96   Excellent

In [ ]:
import calendar

In [ ]:
print(calendar.calendar(2023,1,1,1,5))

                                                    2023

      January               February               March                 April                  May
Mo Tu We Th Fr Sa Su  Mo Tu We Th Fr Sa Su  Mo Tu We Th Fr Sa Su  Mo Tu We Th Fr Sa Su  Mo Tu We Th Fr Sa Su
                   1         1  2  3  4  5         1  2  3  4  5                  1  2   1  2  3  4  5  6  7
 2  3  4  5  6  7  8   6  7  8  9 10 11 12   6  7  8  9 10 11 12   3  4  5  6  7  8  9   8  9 10 11 12 13 14
 9 10 11 12 13 14 15  13 14 15 16 17 18 19  13 14 15 16 17 18 19  10 11 12 13 14 15 16  15 16 17 18 19 20 21
16 17 18 19 20 21 22  20 21 22 23 24 25 26  20 21 22 23 24 25 26  17 18 19 20 21 22 23  22 23 24 25 26 27 28
23 24 25 26 27 28 29  27 28                 27 28 29 30 31        24 25 26 27 28 29 30  29 30 31
30 31

        June                  July                 August              September              October
Mo Tu We Th Fr Sa Su  Mo Tu We Th Fr Sa Su  Mo Tu We Th Fr Sa Su  Mo Tu We Th Fr Sa Su  Mo Tu We Th Fr Sa Su
          1  2  3  4                  1  2      1  2  3  4  5  6               1  2  3                     1
 5  6  7  8  9 10 11   3  4  5  6  7  8  9   7  8  9 10 11 12 13   4  5  6  7  8  9 10   2  3  4  5  6  7  8
12 13 14 15 16 17 18  10 11 12 13 14 15 16  14 15 16 17 18 19 20  11 12 13 14 15 16 17   9 10 11 12 13 14 15
19 20 21 22 23 24 25  17 18 19 20 21 22 23  21 22 23 24 25 26 27  18 19 20 21 22 23 24  16 17 18 19 20 21 22
26 27 28 29 30        24 25 26 27 28 29 30  28 29 30 31           25 26 27 28 29 30     23 24 25 26 27 28 29
                      31                                                                30 31

      November              December
Mo Tu We Th Fr Sa Su  Mo Tu We Th Fr Sa Su
       1  2  3  4  5               1  2  3
 6  7  8  9 10 11 12   4  5  6  7  8  9 10
13 14 15 16 17 18 19  11 12 13 14 15 16 17
20 21 22 23 24 25 26  18 19 20 21 22 23 24
27 28 29 30           25 26 27 28 29 30 31

In [ ]:
calendar.monthcalendar(2026,9)

[[0, 1, 2, 3, 4, 5, 6],
 [7, 8, 9, 10, 11, 12, 13],
 [14, 15, 16, 17, 18, 19, 20],
 [21, 22, 23, 24, 25, 26, 27],
 [28, 29, 30, 0, 0, 0, 0]]

In [ ]:
calendar.monthrange(2026,9)

(calendar.TUESDAY, 30)

In [ ]:
print(calendar.month(2025,7))

     July 2025
Mo Tu We Th Fr Sa Su
    1  2  3  4  5  6
 7  8  9 10 11 12 13
14 15 16 17 18 19 20
21 22 23 24 25 26 27
28 29 30 31

In [ ]:
calendar.isleap(2027)

False

In [ ]:
from datetime import date,datetime

In [ ]:
print(date.today().strftime('%d/%m/%y'))

31/08/26

In [ ]:
print(date.today().strftime("%B-%d-%Y"))

August-31-2026

In [ ]:
now=datetime.now()
print(now)

2026-08-31 12:45:40.654227

In [ ]:
print(datetime.now().strftime("%d/%m/%Y,%H:%M:%S"))

31/08/2026,12:48:22

In [ ]:
x=datetime.now()
x.year

2026

In [ ]:
x.month

8

In [ ]:
x.hour

12

In [ ]:
d1=date(2023,4,5)
d2=date(2023,5,6)
diff=d2-d1
diff

datetime.timedelta(days=31)