In [ ]:
data=[["tom",1,"developer"],
      ["jen",2,"tester"]
      ,["tomy",3,"developer"]]

In [ ]:
import pandas as pd

In [ ]:
df=pd.DataFrame(data)

In [ ]:
df

      0  1          2
0   tom  1  developer
1   jen  2     tester
2  tomy  3  developer

In [ ]:
df1=pd.DataFrame(data,columns=("Employee name","employee id","role"),index=("emp1","emp2","emp3"))

In [ ]:
df1

     Employee name  employee id       role
emp1           tom            1  developer
emp2           jen            2     tester
emp3          tomy            3  developer

In [ ]:
data={
    "ename":["tom","jenny","john"],
    "eid":[1,2,3],
    "role":["developer","tester","developer"]
}

In [ ]:
data=pd.DataFrame(data,index=("emp1","emp2","emp3"))

In [ ]:
data

      ename  eid       role
emp1    tom    1  developer
emp2  jenny    2     tester
emp3   john    3  developer

In [ ]:
data1=pd.read_excel("/content/sample_data/Sample - Superstore.xlsx")

In [ ]:
data1

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-08-11 00:00:00,2016-11-11 00:00:00,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,2016-08-11 00:00:00,2016-11-11 00:00:00,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,2016-12-06 00:00:00,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,2015-11-10 00:00:00,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,2015-11-10 00:00:00,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,CA-2014-110422,1/21/2014,1/23/2014,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028
9990,9991,CA-2017-121258,2/26/2017,2017-03-03 00:00:00,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332
9991,9992,CA-2017-121258,2/26/2017,2017-03-03 00:00:00,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932
9992,9993,CA-2017-121258,2/26/2017,2017-03-03 00:00:00,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4,0.00,13.3200
9993,9994,CA-2017-119914,2017-04-05 00:00:00,2017-09-05 00:00:00,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480

In [ ]:
data1.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-08-11 00:00:00,2016-11-11 00:00:00,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,2016-08-11 00:00:00,2016-11-11 00:00:00,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,2016-12-06 00:00:00,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,2015-11-10 00:00:00,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,2015-11-10 00:00:00,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [ ]:
data1.tail(1)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
9993,9994,CA-2017-119914,2017-04-05 00:00:00,2017-09-05 00:00:00,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.16,2,0.0,72.948

In [ ]:
type(data1)

pandas.core.frame.DataFrame

In [ ]:
data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   object
 3   Ship Date      9994 non-null   object
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), object(15)
memory usage: 1.6+ MB

In [ ]:
data1.describe()

,Row ID,Postal Code,Sales,Quantity,Discount,Profit
count,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000
mean,4997.500000,55190.379428,229.858001,3.789574,0.156203,28.656896
std,2885.163629,32063.693350,623.245101,2.225110,0.206452,234.260108
min,1.000000,1040.000000,0.444000,1.000000,0.000000,-6599.978000
25%,2499.250000,23223.000000,17.280000,2.000000,0.000000,1.728750
50%,4997.500000,56430.500000,54.490000,3.000000,0.200000,8.666500
75%,7495.750000,90008.000000,209.940000,5.000000,0.200000,29.364000
max,9994.000000,99301.000000,22638.480000,14.000000,0.800000,8399.976000

In [ ]:
data1.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='object')

In [ ]:
data1.index

RangeIndex(start=0, stop=9994, step=1)

In [ ]:
data2=pd.read_excel("/content/sample_data/Sample - Superstore.xlsx",index_col="Customer Name")
data2.head(2)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
Customer Name,,,,,,,,,,,,,,,,,,,,
Claire Gute,1,CA-2016-152156,2016-08-11 00:00:00,2016-11-11 00:00:00,Second Class,CG-12520,Consumer,United States,Henderson,Kentucky,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96,2,0.0,41.9136
Claire Gute,2,CA-2016-152156,2016-08-11 00:00:00,2016-11-11 00:00:00,Second Class,CG-12520,Consumer,United States,Henderson,Kentucky,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94,3,0.0,219.5820

In [ ]:
data2.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Segment', 'Country', 'City', 'State', 'Postal Code',
       'Region', 'Product ID', 'Category', 'Sub-Category', 'Product Name',
       'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='object')

In [ ]:
data2['Order ID']

Customer Name
Claire Gute         CA-2016-152156
Claire Gute         CA-2016-152156
Darrin Van Huff     CA-2016-138688
Sean O'Donnell      US-2015-108966
Sean O'Donnell      US-2015-108966
                         ...
Tom Boeckenhauer    CA-2014-110422
Dave Brooks         CA-2017-121258
Dave Brooks         CA-2017-121258
Dave Brooks         CA-2017-121258
Chris Cortes        CA-2017-119914
Name: Order ID, Length: 9994, dtype: object

In [ ]:
data2.loc["Claire Gute"]

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
Customer Name,,,,,,,,,,,,,,,,,,,,
Claire Gute,1,CA-2016-152156,2016-08-11 00:00:00,2016-11-11 00:00:00,Second Class,CG-12520,Consumer,United States,Henderson,Kentucky,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.960,2,0.0,41.9136
Claire Gute,2,CA-2016-152156,2016-08-11 00:00:00,2016-11-11 00:00:00,Second Class,CG-12520,Consumer,United States,Henderson,Kentucky,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.940,3,0.0,219.5820
Claire Gute,5492,CA-2017-164098,1/26/2017,1/27/2017,First Class,CG-12520,Consumer,United States,Houston,Texas,77070,Central,OFF-ST-10000615,Office Supplies,Storage,"SimpliFile Personal File, Black Granite, 15w x...",18.160,2,0.2,1.8160
Claire Gute,6878,US-2015-123918,10/15/2015,10/15/2015,Same Day,CG-12520,Consumer,United States,Dallas,Texas,75217,Central,FUR-FU-10004952,Furniture,Furnishings,C-Line Cubicle Keepers Polyproplyene Holder w/...,131.376,6,0.6,-95.2476
Claire Gute,6879,US-2015-123918,10/15/2015,10/15/2015,Same Day,CG-12520,Consumer,United States,Dallas,Texas,75217,Central,OFF-PA-10003001,Office Supplies,Paper,Xerox 1986,5.344,1,0.2,1.8704

In [ ]:
data2.loc[['Claire Gute','Dave Brooks']]

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
Customer Name,,,,,,,,,,,,,,,,,,,,
Claire Gute,1,CA-2016-152156,2016-08-11 00:00:00,2016-11-11 00:00:00,Second Class,CG-12520,Consumer,United States,Henderson,Kentucky,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.960,2,0.0,41.9136
Claire Gute,2,CA-2016-152156,2016-08-11 00:00:00,2016-11-11 00:00:00,Second Class,CG-12520,Consumer,United States,Henderson,Kentucky,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.940,3,0.0,219.5820
Claire Gute,5492,CA-2017-164098,1/26/2017,1/27/2017,First Class,CG-12520,Consumer,United States,Houston,Texas,77070,Central,OFF-ST-10000615,Office Supplies,Storage,"SimpliFile Personal File, Black Granite, 15w x...",18.160,2,0.2,1.8160
Claire Gute,6878,US-2015-123918,10/15/2015,10/15/2015,Same Day,CG-12520,Consumer,United States,Dallas,Texas,75217,Central,FUR-FU-10004952,Furniture,Furnishings,C-Line Cubicle Keepers Polyproplyene Holder w/...,131.376,6,0.6,-95.2476
Claire Gute,6879,US-2015-123918,10/15/2015,10/15/2015,Same Day,CG-12520,Consumer,United States,Dallas,Texas,75217,Central,OFF-PA-10003001,Office Supplies,Paper,Xerox 1986,5.344,1,0.2,1.8704
Dave Brooks,158,CA-2014-104269,2014-01-03 00:00:00,2014-06-03 00:00:00,Second Class,DB-13060,Consumer,United States,Seattle,Washington,98115,West,FUR-CH-10004063,Furniture,Chairs,Global Deluxe High-Back Manager's Chair,457.568,2,0.2,51.4764
Dave Brooks,434,CA-2016-127369,2016-06-06 00:00:00,2016-07-06 00:00:00,First Class,DB-13060,Consumer,United States,Lowell,Massachusetts,1852,East,OFF-ST-10003306,Office Supplies,Storage,Letter Size Cart,714.300,5,0.0,207.1470
Dave Brooks,903,CA-2017-132353,9/15/2017,9/17/2017,First Class,DB-13060,Consumer,United States,Chicago,Illinois,60653,Central,TEC-PH-10004536,Technology,Phones,Avaya 5420 Digital phone,323.976,3,0.2,20.2485
Dave Brooks,1181,CA-2014-128146,6/21/2014,6/25/2014,Standard Class,DB-13060,Consumer,United States,Lakewood,New Jersey,8701,East,TEC-PH-10004539,Technology,Phones,Wireless Extenders zBoost YX545 SOHO Signal Bo...,1322.930,7,0.0,357.1911
Dave Brooks,1182,CA-2014-128146,6/21/2014,6/25/2014,Standard Class,DB-13060,Consumer,United States,Lakewood,New Jersey,8701,East,OFF-AR-10001919,Office Supplies,Art,"OIC #2 Pencils, Medium Soft",3.760,2,0.0,1.0904
Dave Brooks,6474,CA-2016-113292,3/18/2016,3/20/2016,Second Class,DB-13060,Consumer,United States,Columbia,Tennessee,38401,South,OFF-AP-10003590,Office Supplies,Appliances,Hoover WindTunnel Plus Canister Vacuum,871.800,3,0.2,87.1800
Dave Brooks,6713,CA-2017-107629,12/14/2017,12/14/2017,Same Day,DB-13060,Consumer,United States,Skokie,Illinois,60076,Central,FUR-FU-10002298,Furniture,Furnishings,"Rubbermaid ClusterMat Chairmats, Mat Size- 66""...",266.352,6,0.6,-292.9872
Dave Brooks,6714,CA-2017-107629,12/14/2017,12/14/2017,Same Day,DB-13060,Consumer,United States,Skokie,Illinois,60076,Central,FUR-FU-10004091,Furniture,Furnishings,"Howard Miller 13"" Diameter Goldtone Round Wall...",56.328,3,0.6,-26.7558
Dave Brooks,6715,CA-2017-107629,12/14/2017,12/14/2017,Same Day,DB-13060,Consumer,United States,Skokie,Illinois,60076,Central,TEC-AC-10004510,Technology,Accessories,Logitech Desktop MK120 Mouse and keyboard Combo,39.264,3,0.2,-4.9080
Dave Brooks,6716,CA-2017-107629,12/14/2017,12/14/2017,Same Day,DB-13060,Consumer,United States,Skokie,Illinois,60076,Central,OFF-AR-10002987,Office Supplies,Art,Prismacolor Color Pencil Set,95.232,6,0.2,24.9984
Dave Brooks,9991,CA-2017-121258,2/26/2017,2017-03-03 00:00:00,Standard Class,DB-13060,Consumer,United States,Costa Mesa,California,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.960,2,0.0,15.6332
Dave Brooks,9992,CA-2017-121258,2/26/2017,2017-03-03 00:00:00,Standard Class,DB-13060,Consumer,United States,Costa Mesa,California,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.576,2,0.2,19.3932
Dave Brooks,9993,CA-2017-121258,2/26/2017,2017-03-03 00:00:00,Standard Class,DB-13060,Consumer,United States,Costa Mesa,California,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.600,4,0.0,13.3200

In [ ]:
data2.loc[data2['City'] == 'Chicago']

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
Customer Name,,,,,,,,,,,,,,,,,,,,
Paul Stevenson,67,US-2015-164175,4/30/2015,2015-05-05 00:00:00,Standard Class,PS-18970,Home Office,United States,Chicago,Illinois,60610,Central,FUR-CH-10001146,Furniture,Chairs,"Global Value Mid-Back Manager's Chair, Gray",213.115,5,0.3,-15.2225
Christopher Schild,85,US-2017-119662,11/13/2017,11/16/2017,First Class,CS-12400,Home Office,United States,Chicago,Illinois,60623,Central,OFF-ST-10003656,Office Supplies,Storage,Safco Industrial Wire Shelving,230.376,3,0.2,-48.9549
Rick Bensley,100,CA-2016-158568,8/29/2016,2016-02-09 00:00:00,Standard Class,RB-19465,Home Office,United States,Chicago,Illinois,60610,Central,OFF-PA-10003256,Office Supplies,Paper,Avery Personal Creations Heavyweight Cards,64.624,7,0.2,22.6184
Rick Bensley,101,CA-2016-158568,8/29/2016,2016-02-09 00:00:00,Standard Class,RB-19465,Home Office,United States,Chicago,Illinois,60610,Central,TEC-AC-10001767,Technology,Accessories,SanDisk Ultra 64 GB MicroSDHC Class 10 Memory ...,95.976,3,0.2,-10.7973
Rick Bensley,102,CA-2016-158568,8/29/2016,2016-02-09 00:00:00,Standard Class,RB-19465,Home Office,United States,Chicago,Illinois,60610,Central,OFF-BI-10002609,Office Supplies,Binders,Avery Hidden Tab Dividers for Binding Systems,1.788,3,0.8,-3.0396
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Mark Hamilton,9872,CA-2017-146269,2017-06-10 00:00:00,2017-06-10 00:00:00,Same Day,MH-17455,Consumer,United States,Chicago,Illinois,60623,Central,OFF-ST-10003208,Office Supplies,Storage,Adjustable Depth Letter/Legal Cart,290.336,2,0.2,32.6628
Mark Hamilton,9873,CA-2017-146269,2017-06-10 00:00:00,2017-06-10 00:00:00,Same Day,MH-17455,Consumer,United States,Chicago,Illinois,60623,Central,OFF-AR-10004790,Office Supplies,Art,Staples in misc. colors,19.152,2,0.2,1.1970
Michael Moore,9896,CA-2014-115049,9/26/2014,2014-01-10 00:00:00,Standard Class,MM-17920,Consumer,United States,Chicago,Illinois,60623,Central,TEC-AC-10004859,Technology,Accessories,"Maxell Pro 80 Minute CD-R, 10/Pack",153.824,11,0.2,38.4560
Jennifer Ferguson,9897,CA-2014-156342,6/17/2014,6/20/2014,Second Class,JF-15415,Consumer,United States,Chicago,Illinois,60653,Central,OFF-PA-10001725,Office Supplies,Paper,Xerox 1892,62.016,2,0.2,22.4808
Jeremy Farry,9923,US-2017-162124,2017-06-05 00:00:00,2017-10-05 00:00:00,Standard Class,JF-15490,Consumer,United States,Chicago,Illinois,60653,Central,TEC-AC-10001990,Technology,Accessories,Kensington Orbit Wireless Mobile Trackball for...,191.968,4,0.2,28.7952

In [ ]:
data2[data2['Postal Code']==60623]

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
Customer Name,,,,,,,,,,,,,,,,,,,,
Christopher Schild,85,US-2017-119662,11/13/2017,11/16/2017,First Class,CS-12400,Home Office,United States,Chicago,Illinois,60623,Central,OFF-ST-10003656,Office Supplies,Storage,Safco Industrial Wire Shelving,230.376,3,0.2,-48.9549
Jennifer Braxton,175,US-2014-100853,9/14/2014,9/19/2014,Standard Class,JB-15400,Corporate,United States,Chicago,Illinois,60623,Central,OFF-AP-10000891,Office Supplies,Appliances,Kensington 7 Outlet MasterPiece HOMEOFFICE Pow...,52.448,2,0.8,-131.1200
Jennifer Braxton,176,US-2014-100853,9/14/2014,9/19/2014,Standard Class,JB-15400,Corporate,United States,Chicago,Illinois,60623,Central,OFF-LA-10003148,Office Supplies,Labels,Avery 51,20.160,4,0.2,6.5520
Dan Reichenbach,255,US-2015-159982,11/28/2015,2015-04-12 00:00:00,Standard Class,DR-12880,Corporate,United States,Chicago,Illinois,60623,Central,FUR-FU-10002505,Furniture,Furnishings,Eldon 100 Class Desk Accessories,12.132,9,0.6,-8.4924
Dan Reichenbach,256,US-2015-159982,11/28/2015,2015-04-12 00:00:00,Standard Class,DR-12880,Corporate,United States,Chicago,Illinois,60623,Central,OFF-ST-10004804,Office Supplies,Storage,"Belkin 19"" Vented Equipment Shelf, Black",82.368,2,0.2,-19.5624
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Speros Goranitis,9524,CA-2014-169446,12/19/2014,12/25/2014,Standard Class,SG-20605,Consumer,United States,Chicago,Illinois,60623,Central,OFF-ST-10000419,Office Supplies,Storage,"Rogers Jumbo File, Granite",32.592,3,0.2,-7.7406
Pete Takahito,9809,CA-2017-145093,7/21/2017,7/26/2017,Standard Class,PT-19090,Consumer,United States,Chicago,Illinois,60623,Central,OFF-BI-10001116,Office Supplies,Binders,"Wilson Jones 1"" Hanging DublLock Ring Binders",2.112,2,0.8,-3.3792
Mark Hamilton,9872,CA-2017-146269,2017-06-10 00:00:00,2017-06-10 00:00:00,Same Day,MH-17455,Consumer,United States,Chicago,Illinois,60623,Central,OFF-ST-10003208,Office Supplies,Storage,Adjustable Depth Letter/Legal Cart,290.336,2,0.2,32.6628
Mark Hamilton,9873,CA-2017-146269,2017-06-10 00:00:00,2017-06-10 00:00:00,Same Day,MH-17455,Consumer,United States,Chicago,Illinois,60623,Central,OFF-AR-10004790,Office Supplies,Art,Staples in misc. colors,19.152,2,0.2,1.1970
Michael Moore,9896,CA-2014-115049,9/26/2014,2014-01-10 00:00:00,Standard Class,MM-17920,Consumer,United States,Chicago,Illinois,60623,Central,TEC-AC-10004859,Technology,Accessories,"Maxell Pro 80 Minute CD-R, 10/Pack",153.824,11,0.2,38.4560

In [ ]:
data2[(data2['Postal Code'] == 60623) & (data2['Quantity'] > 6)]

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
Customer Name,,,,,,,,,,,,,,,,,,,,
Dan Reichenbach,255,US-2015-159982,11/28/2015,2015-04-12 00:00:00,Standard Class,DR-12880,Corporate,United States,Chicago,Illinois,60623,Central,FUR-FU-10002505,Furniture,Furnishings,Eldon 100 Class Desk Accessories,12.132,9,0.6,-8.4924
Philisse Overcash,438,CA-2016-147375,2016-12-06 00:00:00,6/14/2016,Second Class,PO-19180,Home Office,United States,Chicago,Illinois,60623,Central,OFF-PA-10001970,Office Supplies,Paper,Xerox 1908,313.488,7,0.2,113.6394
Sibella Parks,1273,US-2016-103646,4/21/2016,4/26/2016,Standard Class,SP-20545,Corporate,United States,Chicago,Illinois,60623,Central,OFF-BI-10002854,Office Supplies,Binders,"Performers Binder/Pad Holder, Black",44.848,8,0.8,-67.2720
Ken Lonsdale,1445,CA-2016-133725,5/23/2016,5/28/2016,Standard Class,KL-16645,Consumer,United States,Chicago,Illinois,60623,Central,TEC-PH-10004165,Technology,Phones,Mitel MiVoice 5330e IP Phone,1979.928,9,0.2,148.4946
Max Ludwig,1972,CA-2017-140242,2017-06-05 00:00:00,2017-11-05 00:00:00,Standard Class,ML-17755,Home Office,United States,Chicago,Illinois,60623,Central,TEC-AC-10004659,Technology,Accessories,Imation Secure+ Hardware Encrypted USB 2.0 Fla...,408.744,7,0.2,76.6395
Emily Grady,3243,CA-2017-114524,3/31/2017,2017-05-04 00:00:00,Second Class,EG-13900,Consumer,United States,Chicago,Illinois,60623,Central,OFF-BI-10002799,Office Supplies,Binders,"SlimView Poly Binder, 3/8""",13.468,13,0.8,-22.8956
Anthony Garverick,5697,CA-2017-126123,10/14/2017,10/18/2017,Standard Class,AG-10765,Home Office,United States,Chicago,Illinois,60623,Central,OFF-BI-10000309,Office Supplies,Binders,"GBC Twin Loop Wire Binding Elements, 9/16"" Spi...",27.396,9,0.8,-42.4638
Brian Stugart,7607,CA-2016-101791,5/27/2016,5/31/2016,Standard Class,BS-11665,Consumer,United States,Chicago,Illinois,60623,Central,OFF-ST-10001496,Office Supplies,Storage,Standard Rollaway File with Lock,1297.368,9,0.2,97.3026
Michael Moore,9896,CA-2014-115049,9/26/2014,2014-01-10 00:00:00,Standard Class,MM-17920,Consumer,United States,Chicago,Illinois,60623,Central,TEC-AC-10004859,Technology,Accessories,"Maxell Pro 80 Minute CD-R, 10/Pack",153.824,11,0.2,38.4560

In [ ]:
data2['Product Name']

Customer Name
Claire Gute                         Bush Somerset Collection Bookcase
Claire Gute         Hon Deluxe Fabric Upholstered Stacking Chairs,...
Darrin Van Huff     Self-Adhesive Address Labels for Typewriters b...
Sean O'Donnell          Bretford CR4500 Series Slim Rectangular Table
Sean O'Donnell                         Eldon Fold 'N Roll Cart System
                                          ...
Tom Boeckenhauer                               Ultra Door Pull Handle
Dave Brooks         Tenex B1-RE Series Chair Mats for Low Pile Car...
Dave Brooks                                     Aastra 57i VoIP phone
Dave Brooks         It's Hot Message Books with Stickers, 2 3/4" x 5"
Chris Cortes        Acco 7-Outlet Masterpiece Power Center, Wihtou...
Name: Product Name, Length: 9994, dtype: object

In [ ]:
data2.iloc[5]

Row ID                                                          6
Order ID                                           CA-2014-115812
Order Date                                    2014-09-06 00:00:00
Ship Date                                               6/14/2014
Ship Mode                                          Standard Class
Customer ID                                              BH-11710
Segment                                                  Consumer
Country                                             United States
City                                                  Los Angeles
State                                                  California
Postal Code                                                 90032
Region                                                       West
Product ID                                        FUR-FU-10001487
Category                                                Furniture
Sub-Category                                          Furnishings
Product Name    Eldon Expressions Wood and Plastic Desk Access...
Sales                                                       48.86
Quantity                                                        7
Discount                                                      0.0
Profit                                                    14.1694
Name: Brosina Hoffman, dtype: object

In [ ]:
data2.iloc[:,3]

Customer Name
Claire Gute         2016-11-11 00:00:00
Claire Gute         2016-11-11 00:00:00
Darrin Van Huff               6/16/2016
Sean O'Donnell               10/18/2015
Sean O'Donnell               10/18/2015
                           ...
Tom Boeckenhauer              1/23/2014
Dave Brooks         2017-03-03 00:00:00
Dave Brooks         2017-03-03 00:00:00
Dave Brooks         2017-03-03 00:00:00
Chris Cortes        2017-09-05 00:00:00
Name: Ship Date, Length: 9994, dtype: object

In [ ]:
data2.iloc[0:2,9]

Customer Name
Claire Gute    Kentucky
Claire Gute    Kentucky
Name: State, dtype: object

In [ ]:
data2.iloc[0:4,2:4]

                          Order Date            Ship Date
Customer Name
Claire Gute      2016-08-11 00:00:00  2016-11-11 00:00:00
Claire Gute      2016-08-11 00:00:00  2016-11-11 00:00:00
Darrin Van Huff  2016-12-06 00:00:00            6/16/2016
Sean O'Donnell   2015-11-10 00:00:00           10/18/2015

Handling null values

In [ ]:
import pandas as pd
import numpy as np

data = pd.DataFrame({
    'Name': ['A', np.nan, 'C'],
    'Age': [20, np.nan, 22],
    'Marks': [80, 90, np.nan]
})
data=pd.DataFrame(data)
data

  Name   Age  Marks
0    A  20.0   80.0
1  NaN   NaN   90.0
2    C  22.0    NaN

In [ ]:
data.fillna(0)

  Name   Age  Marks
0    A  20.0   80.0
1    0   0.0   90.0
2    C  22.0    0.0

In [ ]:
data.isnull()

    Name    Age  Marks
0  False  False  False
1   True   True  False
2  False  False   True

In [ ]:
data.isnull().sum()

Name     1
Age      1
Marks    1
dtype: int64

In [ ]:
mean1=data['Age'].mean()
int(mean1)

21

In [ ]:
median1=data['Marks'].median()
median1

85.0

In [ ]:
mode1=data['Name'].mode()
mode1

0    A
1    C
Name: Name, dtype: object

In [ ]:
mode1=data['Name'].mode()[0]

In [ ]:
dframe=data.fillna({'Age':mean1,'Marks':median1,'Name':mode1})
dframe

  Name   Age  Marks
0    A  20.0   80.0
1    A  21.0   90.0
2    C  22.0   85.0

In [ ]:
data

  Name   Age  Marks
0    A  20.0   80.0
1  NaN   NaN   90.0
2    C  22.0    NaN

In [ ]:
backup=data.copy()

In [ ]:
data.fillna({'Age':mean1,'Marks':median1,'Name':mode1},inplace=True)

In [ ]:
data

  Name   Age  Marks
0    A  20.0   80.0
1    A  21.0   90.0
2    C  22.0   85.0

In [ ]:
backup

  Name   Age  Marks
0    A  20.0   80.0
1  NaN   NaN   90.0
2    C  22.0    NaN

In [ ]:
newdf=data.fillna({'Age':mean1,'Marks':median1,'Name':mode1})

In [ ]:
newdf

  Name   Age  Marks
0    A  20.0   80.0
1    A  21.0   90.0
2    C  22.0   85.0

In [ ]:
data

  Name   Age  Marks
0    A  20.0   80.0
1    A  21.0   90.0
2    C  22.0   85.0

In [ ]:
backup.dropna()

  Name   Age  Marks
0    A  20.0   80.0

In [ ]:
backup

  Name   Age  Marks
0    A  20.0   80.0
1  NaN   NaN   90.0
2    C  22.0    NaN

In [ ]:
data = [
    [1,2,3,'M',1],
    [np.nan,5,6,np.nan,2],
    [7,np.nan,8,'F',3],
    [np.nan,np.nan,np.nan,'F',4]
]

In [ ]:
data=pd.DataFrame(data,columns=['a','b','c','d','e'])

In [ ]:
data.dropna()

     a    b    c  d  e
0  1.0  2.0  3.0  M  1

In [ ]:
data

     a    b    c    d  e
0  1.0  2.0  3.0    M  1
1  NaN  5.0  6.0  NaN  2
2  7.0  NaN  8.0    F  3
3  NaN  NaN  NaN    F  4

In [ ]:
data.dropna(axis=0)

     a    b    c  d  e
0  1.0  2.0  3.0  M  1

In [ ]:
data.dropna(axis=1)

   e
0  1
1  2
2  3
3  4

Handling Duplicates

In [ ]:
dupli=pd.DataFrame({'name':['a','a','a','b','c','c','d','e'],
       'id':[1,1,3,2,3,2,1,4]})

In [ ]:
dupli.duplicated()

0    False
1     True
2    False
3    False
4    False
5    False
6    False
7    False
dtype: bool

In [ ]:
ddup = pd.DataFrame({'col1':['A','A','B','B','B'],'col2':[2,2,2,3,3]})
ddup

  col1  col2
0    A     2
1    A     2
2    B     2
3    B     3
4    B     3

In [ ]:
ddup.duplicated()

0    False
1     True
2    False
3    False
4     True
dtype: bool

In [ ]:
ddup.duplicated('col1')

0    False
1     True
2    False
3     True
4     True
dtype: bool

In [ ]:
ddup.duplicated().sum()

np.int64(2)

In [ ]:
ddup.drop_duplicates()

  col1  col2
0    A     2
2    B     2
3    B     3

In [ ]:
ddup

  col1  col2
0    A     2
1    A     2
2    B     2
3    B     3
4    B     3

In [ ]:
ddup.drop_duplicates(inplace=True)

In [ ]:
ddup

  col1  col2
0    A     2
2    B     2
3    B     3

In [ ]:
ddup.rename(columns={'col1':'Name','col2':'Id'},inplace=True)
ddup

  Name  Id
0    A   2
2    B   2
3    B   3

Connecting Data frames

In [ ]:
import pandas as pd

df1 = pd.DataFrame({
    'Name': ['A', 'B'],
    'Age': [20, 21]
})

df2 = pd.DataFrame({
    'Name': ['C', 'D'],
    'Age': [22, 23]
})

In [ ]:
pd.concat([df1,df2])

  Name  Age
0    A   20
1    B   21
0    C   22
1    D   23

In [ ]:
pd.concat([df1,df2],ignore_index=True)

  Name  Age
0    A   20
1    B   21
2    C   22
3    D   23

In [ ]:
customers = pd.DataFrame({
    'CustomerID': [1, 2, 3],
    'Name': ['Ravi', 'Sita', 'John']
})

In [ ]:
orders = pd.DataFrame({
    'CustomerID': [1, 2, 3],
    'Amount': [500, 700, 300]
})

In [ ]:
pd.merge(customers,orders,on="CustomerID")

   CustomerID  Name  Amount
0           1  Ravi     500
1           2  Sita     700
2           3  John     300

In [ ]:
pd.merge(customers,orders,on="CustomerID",how="inner")

   CustomerID  Name  Amount
0           1  Ravi     500
1           2  Sita     700
2           3  John     300

In [ ]:
pd.merge(customers,orders,on="CustomerID",how="outer")

   CustomerID  Name  Amount
0           1  Ravi     500
1           2  Sita     700
2           3  John     300

In [ ]:
d1 = {'movieid':[1,2,3,4,5],
      'title':['Leo','Jawan','Gadar','Pathan','Uri']}
movies = pd.DataFrame(d1)

In [ ]:
d2 = {'memid':[1,2,3,4],
      'name':['Tom','Tim','Jon','Jim'],
      'movieid':[1,np.nan,3,5]}
members = pd.DataFrame(d2)

In [ ]:
pd.merge(movies,members,on="movieid")

   movieid  title  memid name
0        1    Leo      1  Tom
1        3  Gadar      3  Jon
2        5    Uri      4  Jim

In [ ]:
pd.merge(movies,members,on="movieid",how="inner")

   movieid  title  memid name
0        1    Leo      1  Tom
1        3  Gadar      3  Jon
2        5    Uri      4  Jim

In [ ]:
pd.merge(movies,members,on="movieid",how="outer")

   movieid   title  memid name
0      1.0     Leo    1.0  Tom
1      2.0   Jawan    NaN  NaN
2      3.0   Gadar    3.0  Jon
3      4.0  Pathan    NaN  NaN
4      5.0     Uri    4.0  Jim
5      NaN     NaN    2.0  Tim

In [ ]:
pd.merge(movies,members,on="movieid",how="left")

   movieid   title  memid name
0        1     Leo    1.0  Tom
1        2   Jawan    NaN  NaN
2        3   Gadar    3.0  Jon
3        4  Pathan    NaN  NaN
4        5     Uri    4.0  Jim

In [ ]:
pd.merge(movies,members,on="movieid",how="right")

   movieid  title  memid name
0      1.0    Leo      1  Tom
1      NaN    NaN      2  Tim
2      3.0  Gadar      3  Jon
3      5.0    Uri      4  Jim

In [ ]:
df1 = pd.DataFrame({
    'Name': ['A', 'B', 'C']
})

df2 = pd.DataFrame({
    'Marks': [80, 90, 85]
})

In [ ]:
df1.join(df2)

  Name  Marks
0    A     80
1    B     90
2    C     85

In [ ]:
sort1=pd.read_excel("/content/sample_data/Sample - Superstore.xlsx")
sort1.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='object')

In [ ]:
sort1.sort_values('Profit')

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
7772,7773,CA-2016-108196,11/25/2016,2016-02-12 00:00:00,Standard Class,CS-12505,Cindy Stewart,Consumer,United States,Lancaster,...,43130,East,TEC-MA-10000418,Technology,Machines,Cubify CubeX 3D Printer Double Head Print,4499.985,5,0.7,-6599.9780
683,684,US-2017-168116,2017-04-11 00:00:00,2017-04-11 00:00:00,Same Day,GT-14635,Grant Thornton,Corporate,United States,Burlington,...,27217,South,TEC-MA-10004125,Technology,Machines,Cubify CubeX 3D Printer Triple Head Print,7999.980,4,0.5,-3839.9904
9774,9775,CA-2014-169019,7/26/2014,7/30/2014,Standard Class,LF-17185,Luke Foster,Consumer,United States,San Antonio,...,78207,Central,OFF-BI-10004995,Office Supplies,Binders,GBC DocuBind P400 Electric Binding System,2177.584,8,0.8,-3701.8928
3011,3012,CA-2017-134845,4/17/2017,4/23/2017,Standard Class,SR-20425,Sharelle Roach,Home Office,United States,Louisville,...,80027,West,TEC-MA-10000822,Technology,Machines,Lexmark MX611dhe Monochrome Laser Printer,2549.985,5,0.7,-3399.9800
4991,4992,US-2017-122714,2017-07-12 00:00:00,12/13/2017,Standard Class,HG-14965,Henry Goldwyn,Corporate,United States,Chicago,...,60653,Central,OFF-BI-10001120,Office Supplies,Binders,Ibico EPK-21 Electric Binding System,1889.990,5,0.8,-2929.4845
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4098,4099,CA-2014-116904,9/23/2014,9/28/2014,Standard Class,SC-20095,Sanjit Chand,Consumer,United States,Minneapolis,...,55407,Central,OFF-BI-10001120,Office Supplies,Binders,Ibico EPK-21 Electric Binding System,9449.950,5,0.0,4630.4755
9039,9040,CA-2016-117121,12/17/2016,12/21/2016,Standard Class,AB-10105,Adrian Barton,Consumer,United States,Detroit,...,48205,Central,OFF-BI-10000545,Office Supplies,Binders,GBC Ibimaster 500 Manual ProClick Binding System,9892.740,13,0.0,4946.3700
4190,4191,CA-2017-166709,11/17/2017,11/22/2017,Standard Class,HL-15040,Hunter Lopez,Consumer,United States,Newark,...,19711,East,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,10499.970,3,0.0,5039.9856
8153,8154,CA-2017-140151,3/23/2017,3/25/2017,First Class,RB-19360,Raymond Buch,Consumer,United States,Seattle,...,98115,West,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,13999.960,4,0.0,6719.9808
6826,6827,CA-2016-118689,2016-02-10 00:00:00,2016-09-10 00:00:00,Standard Class,TC-20980,Tamara Chand,Corporate,United States,Lafayette,...,47905,Central,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,17499.950,5,0.0,8399.9760

In [ ]:
sort1[['Category','Profit','Customer ID']].sort_values('Profit')

             Category     Profit Customer ID
7772       Technology -6599.9780    CS-12505
683        Technology -3839.9904    GT-14635
9774  Office Supplies -3701.8928    LF-17185
3011       Technology -3399.9800    SR-20425
4991  Office Supplies -2929.4845    HG-14965
...               ...        ...         ...
4098  Office Supplies  4630.4755    SC-20095
9039  Office Supplies  4946.3700    AB-10105
4190       Technology  5039.9856    HL-15040
8153       Technology  6719.9808    RB-19360
6826       Technology  8399.9760    TC-20980

[9994 rows x 3 columns]

In [ ]:
sort1[['Category','Profit','Customer ID']].sort_values('Category',ascending=False)

        Category    Profit Customer ID
2445  Technology   74.8142    AF-10870
5800  Technology   43.1976    MN-17935
2464  Technology   36.9873    CS-12460
8559  Technology   35.9850    LA-16780
8560  Technology   14.8365    LA-16780
...          ...       ...         ...
3831   Furniture   26.6490    LS-17230
3834   Furniture  -34.9176    MY-18295
8068   Furniture    6.0876    NS-18640
8070   Furniture -187.3815    JM-15250
0      Furniture   41.9136    CG-12520

[9994 rows x 3 columns]

In [ ]:
sort1[['Category','Profit','Customer ID']].sort_index()

             Category    Profit Customer ID
0           Furniture   41.9136    CG-12520
1           Furniture  219.5820    CG-12520
2     Office Supplies    6.8714    DV-13045
3           Furniture -383.0310    SO-20335
4     Office Supplies    2.5164    SO-20335
...               ...       ...         ...
9989        Furniture    4.1028    TB-21400
9990        Furniture   15.6332    DB-13060
9991       Technology   19.3932    DB-13060
9992  Office Supplies   13.3200    DB-13060
9993  Office Supplies   72.9480    CC-12220

[9994 rows x 3 columns]

In [ ]:
sort1['Quantity'].apply(lambda x:'Best Product' if x>10 else 'Sales must be improved')

0       Sales must be improved
1       Sales must be improved
2       Sales must be improved
3       Sales must be improved
4       Sales must be improved
                 ...
9989    Sales must be improved
9990    Sales must be improved
9991    Sales must be improved
9992    Sales must be improved
9993    Sales must be improved
Name: Quantity, Length: 9994, dtype: object

In [ ]:
sort1['Product sales']=sort1['Quantity'].apply(lambda x:'Best Product' if x>10 else 'Sales must be improved')

In [ ]:
sort1

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Product sales
0,1,CA-2016-152156,2016-08-11 00:00:00,2016-11-11 00:00:00,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,Sales must be improved
1,2,CA-2016-152156,2016-08-11 00:00:00,2016-11-11 00:00:00,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,Sales must be improved
2,3,CA-2016-138688,2016-12-06 00:00:00,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714,Sales must be improved
3,4,US-2015-108966,2015-11-10 00:00:00,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,Sales must be improved
4,5,US-2015-108966,2015-11-10 00:00:00,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164,Sales must be improved
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,CA-2014-110422,1/21/2014,1/23/2014,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028,Sales must be improved
9990,9991,CA-2017-121258,2/26/2017,2017-03-03 00:00:00,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332,Sales must be improved
9991,9992,CA-2017-121258,2/26/2017,2017-03-03 00:00:00,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932,Sales must be improved
9992,9993,CA-2017-121258,2/26/2017,2017-03-03 00:00:00,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4,0.00,13.3200,Sales must be improved
9993,9994,CA-2017-119914,2017-04-05 00:00:00,2017-09-05 00:00:00,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480,Sales must be improved

In [ ]:
import math

In [ ]:
math.pow(2,5)

32.0

In [ ]:
dir(math)

['__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'acos',
 'acosh',
 'asin',
 'asinh',
 'atan',
 'atan2',
 'atanh',
 'cbrt',
 'ceil',
 'comb',
 'copysign',
 'cos',
 'cosh',
 'degrees',
 'dist',
 'e',
 'erf',
 'erfc',
 'exp',
 'exp2',
 'expm1',
 'fabs',
 'factorial',
 'floor',
 'fmod',
 'frexp',
 'fsum',
 'gamma',
 'gcd',
 'hypot',
 'inf',
 'isclose',
 'isfinite',
 'isinf',
 'isnan',
 'isqrt',
 'lcm',
 'ldexp',
 'lgamma',
 'log',
 'log10',
 'log1p',
 'log2',
 'modf',
 'nan',
 'nextafter',
 'perm',
 'pi',
 'pow',
 'prod',
 'radians',
 'remainder',
 'sin',
 'sinh',
 'sqrt',
 'sumprod',
 'tan',
 'tanh',
 'tau',
 'trunc',
 'ulp']

In [ ]:
math.trunc(23.5667)

23

In [ ]:
round(23.567,1)

23.6

In [ ]:
math.log(2,4)

0.5

In [ ]:
math.pi

3.141592653589793

In [ ]:
math.tan(45)

1.6197751905438615

Calendars

In [ ]:
import calendar

In [ ]:
dir(calendar)

['APRIL',
 'AUGUST',
 'Calendar',
 'DECEMBER',
 'Day',
 'EPOCH',
 'FEBRUARY',
 'FRIDAY',
 'HTMLCalendar',
 'IllegalMonthError',
 'IllegalWeekdayError',
 'IntEnum',
 'JANUARY',
 'JULY',
 'JUNE',
 'LocaleHTMLCalendar',
 'LocaleTextCalendar',
 'MARCH',
 'MAY',
 'MONDAY',
 'Month',
 'NOVEMBER',
 'OCTOBER',
 'SATURDAY',
 'SEPTEMBER',
 'SUNDAY',
 'THURSDAY',
 'TUESDAY',
 'TextCalendar',
 'WEDNESDAY',
 '_EPOCH_ORD',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '_colwidth',
 '_get_default_locale',
 '_locale',
 '_localized_day',
 '_localized_month',
 '_monthlen',
 '_nextmonth',
 '_prevmonth',
 '_spacing',
 '_validate_month',
 'c',
 'calendar',
 'datetime',
 'day_abbr',
 'day_name',
 'different_locale',
 'error',
 'firstweekday',
 'format',
 'formatstring',
 'global_enum',
 'isleap',
 'leapdays',
 'main',
 'mdays',
 'month',
 'month_abbr',
 'month_name',
 'monthcalendar',
 'monthrange',
 'prcal',
 'prmonth',
 'prweek',
 'repeat',
 'setfirstweekday',
 'sys',
 'timegm',
 'warnings',
 'week',
 'weekday',
 'weekheader']

In [ ]:
print(calendar.month(2026,8))

    August 2026
Mo Tu We Th Fr Sa Su
                1  2
 3  4  5  6  7  8  9
10 11 12 13 14 15 16
17 18 19 20 21 22 23
24 25 26 27 28 29 30
31

In [ ]:
print(calendar.isleap(2026))

False

In [ ]:
print("Calendar of the year 2024 is : ")

print(calendar.calendar(2024, 1, 1, 5, 6))

Calendar of the year 2024 is :
                                                                       2024

      January                  February                  March                    April                     May                      June
Mo Tu We Th Fr Sa Su     Mo Tu We Th Fr Sa Su     Mo Tu We Th Fr Sa Su     Mo Tu We Th Fr Sa Su     Mo Tu We Th Fr Sa Su     Mo Tu We Th Fr Sa Su
 1  2  3  4  5  6  7               1  2  3  4                  1  2  3      1  2  3  4  5  6  7            1  2  3  4  5                     1  2
 8  9 10 11 12 13 14      5  6  7  8  9 10 11      4  5  6  7  8  9 10      8  9 10 11 12 13 14      6  7  8  9 10 11 12      3  4  5  6  7  8  9
15 16 17 18 19 20 21     12 13 14 15 16 17 18     11 12 13 14 15 16 17     15 16 17 18 19 20 21     13 14 15 16 17 18 19     10 11 12 13 14 15 16
22 23 24 25 26 27 28     19 20 21 22 23 24 25     18 19 20 21 22 23 24     22 23 24 25 26 27 28     20 21 22 23 24 25 26     17 18 19 20 21 22 23
29 30 31                 26 27 28 29              25 26 27 28 29 30 31     29 30                    27 28 29 30 31           24 25 26 27 28 29 30

        July                    August                 September                 October                  November                 December
Mo Tu We Th Fr Sa Su     Mo Tu We Th Fr Sa Su     Mo Tu We Th Fr Sa Su     Mo Tu We Th Fr Sa Su     Mo Tu We Th Fr Sa Su     Mo Tu We Th Fr Sa Su
 1  2  3  4  5  6  7               1  2  3  4                        1         1  2  3  4  5  6                  1  2  3                        1
 8  9 10 11 12 13 14      5  6  7  8  9 10 11      2  3  4  5  6  7  8      7  8  9 10 11 12 13      4  5  6  7  8  9 10      2  3  4  5  6  7  8
15 16 17 18 19 20 21     12 13 14 15 16 17 18      9 10 11 12 13 14 15     14 15 16 17 18 19 20     11 12 13 14 15 16 17      9 10 11 12 13 14 15
22 23 24 25 26 27 28     19 20 21 22 23 24 25     16 17 18 19 20 21 22     21 22 23 24 25 26 27     18 19 20 21 22 23 24     16 17 18 19 20 21 22
29 30 31                 26 27 28 29 30 31        23 24 25 26 27 28 29     28 29 30 31              25 26 27 28 29 30        23 24 25 26 27 28 29
                                                  30                                                                         30 31

In [ ]:
print(calendar.calendar(2026))

                                  2026

      January                   February                   March
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
          1  2  3  4                         1                         1
 5  6  7  8  9 10 11       2  3  4  5  6  7  8       2  3  4  5  6  7  8
12 13 14 15 16 17 18       9 10 11 12 13 14 15       9 10 11 12 13 14 15
19 20 21 22 23 24 25      16 17 18 19 20 21 22      16 17 18 19 20 21 22
26 27 28 29 30 31         23 24 25 26 27 28         23 24 25 26 27 28 29
                                                    30 31

       April                      May                       June
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
       1  2  3  4  5                   1  2  3       1  2  3  4  5  6  7
 6  7  8  9 10 11 12       4  5  6  7  8  9 10       8  9 10 11 12 13 14
13 14 15 16 17 18 19      11 12 13 14 15 16 17      15 16 17 18 19 20 21
20 21 22 23 24 25 26      18 19 20 21 22 23 24      22 23 24 25 26 27 28
27 28 29 30               25 26 27 28 29 30 31      29 30

        July                     August                  September
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
       1  2  3  4  5                      1  2          1  2  3  4  5  6
 6  7  8  9 10 11 12       3  4  5  6  7  8  9       7  8  9 10 11 12 13
13 14 15 16 17 18 19      10 11 12 13 14 15 16      14 15 16 17 18 19 20
20 21 22 23 24 25 26      17 18 19 20 21 22 23      21 22 23 24 25 26 27
27 28 29 30 31            24 25 26 27 28 29 30      28 29 30
                          31

      October                   November                  December
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
          1  2  3  4                         1          1  2  3  4  5  6
 5  6  7  8  9 10 11       2  3  4  5  6  7  8       7  8  9 10 11 12 13
12 13 14 15 16 17 18       9 10 11 12 13 14 15      14 15 16 17 18 19 20
19 20 21 22 23 24 25      16 17 18 19 20 21 22      21 22 23 24 25 26 27
26 27 28 29 30 31         23 24 25 26 27 28 29      28 29 30 31
                          30

In [ ]:
print(calendar.month(2025,10,2,1))

    October 2025
Mo Tu We Th Fr Sa Su
       1  2  3  4  5
 6  7  8  9 10 11 12
13 14 15 16 17 18 19
20 21 22 23 24 25 26
27 28 29 30 31

In [ ]:
calendar.monthcalendar(2026,8)

[[0, 0, 0, 0, 0, 1, 2],
 [3, 4, 5, 6, 7, 8, 9],
 [10, 11, 12, 13, 14, 15, 16],
 [17, 18, 19, 20, 21, 22, 23],
 [24, 25, 26, 27, 28, 29, 30],
 [31, 0, 0, 0, 0, 0, 0]]

In [ ]:
from datetime import date

In [ ]:
today=date.today()
today

datetime.date(2026, 8, 20)

In [ ]:
d1 = today.strftime("%d/%m/%Y")
print("d1 =", d1)

d1 = 20/08/2026

In [ ]:
d1 = today.strftime("%B/%m/%Y")
print("d1 =", d1)

d1 = August/08/2026

In [ ]:
d1 = today.strftime("%d/%B/%Y")
print("d1 =", d1)

d1 = 20/August/2026

In [ ]:
d1 = today.strftime("%b-%m-%Y")
print("d1 =", d1)

d1 = Aug-08-2026